### PR TITLE
Additional prometheus labels from envvars

### PR DESCRIPTION
**Pull request by andlaz**
Hi,

i have a use case where i need to add helm/kubernetes metadata on to metrics scraped from Cassandra. I figured the easiest way is for me to set these as env vars in the metrics side car. Here's a quick stab at an implementation.

Let me know what you think.

thanks,
Andras

### CODE REVIEW

**Comment by andlaz** [comment]
Forgot to add tests. They are there now although basic, as anything more robust would require some refactoring on master.

**Comment by erebe** [comment]
Hello,

Thanks for the PR and sorry for the delay, I was off for vacation.
I will check the code today or tomorrow and be back to you.

Thanks again for taking time to write the PR

**Comment by geobeau** [comment]
Out of curiosity, when using Prometheus, it is usually recommended to append those kind of labels using metric relabelling and metadata from the service discovery at scrape time. Is there anything preventing you from doing that ?

**Comment by andlaz** [comment]
thanks! i’m using the operator to dynamically configure targets, (haven’t looked in to relabeling) and i know that it can also collect labels directly from some kube objects ( service, it’s CRD servicemonitor, etc ). My problem is the lifecycle of my deployment of the application is often not tied to these for various reasons ( i need to keep service and other resources around )

**Pull request merged**
