### PR TITLE
Rename "scrap" to "scrape".

### PR DESCRIPTION
**Pull request by mpereira**
Was this the intended word to be used?

### CODE REVIEW

**Comment by erebe** [comment]
Thanks :)

**Comment by porridge** [comment]
FTR, I just learned about this backwards-incompatible change [the hard way](https://github.com/mesosphere/kudo-cassandra-operator/pull/56#issuecomment-593903798) :boom: 
It might be good to at least drop a line into the [2.3.1 release notes](https://github.com/criteo/cassandra_exporter/releases/tag/2.3.1) to warn other users about this...

**Comment by porridge** [comment]
Alternatively, you might decide to still support the old spelling as deprecated, and drop that at the next major version bump...

**Comment by erebe** [comment]
My bad, I was sure to had rejected this PR I didn't want to cause breaking change for end-user as scrap is a valid term also used by Prometheus.

**Comment by erebe** [comment]
It is reverted in 2.3.4, you will need to update again your config for it to be the old way.

Again sorry about that... and thank you for reporting the issue

**Pull request merged**
