### PR TITLE
Adding Grafana dashboards

### PR DESCRIPTION
**Pull request by deimosfr**

### CODE REVIEW

**Comment by erebe** [comment]
In the cassandra default dashboard, every keyspaces of every clusters are mixed together.
Can you rename your namespace into a cluster variable/label ?

**Comment by deimosfr** [comment]
Ok, but which expression should the template/variable should be made FYPOV ?

**Comment by erebe** [comment]
Either use a dedicated label cluster that will be mandatory or use the job name as a differentiator
In any case the user will have to modify its scraping config in order to get it
So something like that `label_values(cassandra_stats{job="cassandra"}, cluster)`, add an all value in the template also in order for the dashboard to work even if it haven't this label.

I will look if I can retrieve the cluster name in the jmx entries in order to get the cluster label natively

**Comment by erebe** [comment]
Legends formats are remplaced by your template engine ...

**Comment by erebe** [comment]
https://github.com/criteo/cassandra_exporter/issues/8

**Comment by erebe** [comment]
:+1:

**Pull request merged**
